ALTER TABLE TB_PRODUCTS ADD COLUMN sku VARCHAR(100) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN description VARCHAR(1000);
ALTER TABLE TB_PRODUCTS ADD COLUMN category VARCHAR(255);
ALTER TABLE TB_PRODUCTS ADD COLUMN brand VARCHAR(255);
ALTER TABLE TB_PRODUCTS ADD COLUMN unit VARCHAR(50);
ALTER TABLE TB_PRODUCTS ADD COLUMN stock_quantity INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN min_stock INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN cost_price FLOAT;
ALTER TABLE TB_PRODUCTS ADD COLUMN sale_price FLOAT;
ALTER TABLE TB_PRODUCTS ADD COLUMN currency VARCHAR(3) DEFAULT 'BRL' NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN active BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE TB_PRODUCTS ADD COLUMN image_url VARCHAR(1024);
ALTER TABLE TB_PRODUCTS ADD COLUMN barcode VARCHAR(128);

ALTER TABLE TB_PRODUCTS ADD CONSTRAINT uk_tb_products_sku UNIQUE (sku);
